### ISSUE TITLE
P12证书

### ISSUE THREAD

**Issue by zhangmingjing0** [KOP-XIAO/QuantumultX#1]
你好，我发现您的QuantumultX远程配置QuantumultX_Profiles.conf被引入到[QX不完全教程](https://www.notion.so/Quantumult-X-1d32ddc6e61c4892ad2ec5ea47f00917#b530c639bbca4215b4a309bd5b5f1f05)
配置中包含了P12证书，又很可能被很多小白使用。如果此证书被人利用，部分人可能会受到到中间人攻击。
为保护您和他人的隐私，建议您删除配置中的P12证书信息。

**Comment by KOP-XIAO** [comment]
好的
