### ISSUE TITLE
可以给Quantumult X 资源解析器添加一个将stash重写规则(stoverride格式)转换为quantumultx重写规则的功能吗

### ISSUE THREAD

**Issue by PKC278** [KOP-XIAO/QuantumultX#100]
这是stash的重写规则`https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/Stash/AdvertisingLite/AdvertisingLite.stoverride`
这是对应的quantumultx重写规则`https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/AdvertisingLite/AdvertisingLite.conf`

**Comment by KOP-XIAO** [comment]
没意义
