### ISSUE TITLE
rrname bug?

### ISSUE THREAD

**Issue by okami-chen** [KOP-XIAO/QuantumultX#104]
订阅链接后面增加#emoji=2&sort=🇸🇬>🇺🇸>🇭🇰>🇯🇵>🇰🇷>🇨🇳>🇨🇦>🇦🇺>🇬🇧>🇫🇷>🇨🇦>🇮🇪>🇮🇳>🇷🇺>🏴‍☠️&info=1&del=1&out=到期+剩余&rrname=ESNC%20-%20@,使用了rrname=ESNC%20-%20@导致国旗不正确,改成rrname=Esnc%20-%20@就正确了,如果增加ESNC前缀的同时国旗能正确显示

**Comment by KOP-XIAO** [comment]
应该是 ES 匹配了西班牙缩写造成的吧
