### ISSUE TITLE
surge脚本正则中带有 逗号  ,   时会解析错误

### ISSUE THREAD

**Issue by chengkongyiban** [KOP-XIAO/QuantumultX#105]
以下是一个测试用的模块
https://raw.githubusercontent.com/chengkongyiban/Surge/main/modules/test2.sgmodule
![image](https://github.com/KOP-XIAO/QuantumultX/assets/48396581/064c9086-b04d-4a5c-9d91-f9f999d53e78)

解析时报错如上图

**Comment by KOP-XIAO** [comment]
更新

**Comment by chengkongyiban** [comment]
好了，谢谢
