### ISSUE TITLE
更新后，解析器异常

### ISSUE THREAD

**Issue by KyleRicardo** [KOP-XIAO/QuantumultX#109]
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Video/Netflix.list

解析以上规则时候，抛出异常：
Resource Parser Exception
{"line":1}

**Comment by KOP-XIAO** [comment]
![2024-01-06 21 27 04](https://github.com/KOP-XIAO/QuantumultX/assets/45581750/16fcb386-d09b-48c6-967f-b713239d2fbd)

**Comment by KyleRicardo** [comment]
看了下大佬的截图，资源解析器用的是raw链接，问题就在这里。

我之前是jsdelivr的cdn链接，更新不了，然后就用了https://github.com/KOP-XIAO/QuantumultX/blob/master/Scripts/resource-parser.js 这个链接，能更新了但是其实是有问题的，下面显示的readme格式都不对。

改成https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js 之后，好了。

感谢shawn大佬。
