### ISSUE TITLE
在QuantumultX上使用此脚本重写youtube资源路径报错

### ISSUE THREAD

**Issue by wjezxujian** [KOP-XIAO/QuantumultX#114]
![IMG_3061](https://github.com/KOP-XIAO/QuantumultX/assets/4151526/9d945451-b309-4503-8aa0-70e6a853b36d)
![IMG_3062](https://github.com/KOP-XIAO/QuantumultX/assets/4151526/e4a0798d-bf67-4270-a9e9-213b92500b89)

资源路径为：https://raw.githubusercontent.com/Maasea/sgmodule/master/YouTube.Enhance.sgmodule

**Comment by KOP-XIAO** [comment]
更新
