### ISSUE TITLE
in/out 参数不起作用

### ISSUE THREAD

**Issue by xixaxoqiqaqo** [KOP-XIAO/QuantumultX#37]
- sub&in=中文, 提示 The file doesn’t exist
- in/out参数不起作用?
- 版本 1.0.19

**Comment by LucaLin233** [comment]
> * sub&in=中文, 提示 The file doesn’t exist
> * in/out参数不起作用?
> * 版本 1.0.19

应该是#吧不是&

**Comment by xixaxoqiqaqo** [comment]
> > * sub&in=中文, 提示 The file doesn’t exist
> > * in/out参数不起作用?
> > * 版本 1.0.19
> 
> 应该是#吧不是&

确实忘了 # ，😅
