### ISSUE TITLE
𝘀𝗼𝗿𝘁参数不生效？

### ISSUE THREAD

**Issue by loyle5** [KOP-XIAO/QuantumultX#38]
#𝗲𝗺𝗼𝗷𝗶=1&𝘂𝗱𝗽=1&𝘁𝗳𝗼=1&𝐫𝐞𝐧𝐚𝐦𝐞=@「$emoji1」&𝘀𝗼𝗿𝘁=🇭🇰>🇸🇬>🇯🇵>🇺🇸
无法按sort顺序排序
是参数写的不对吗？
前面订阅连接写SSR和clash的都不行

**Comment by KOP-XIAO** [comment]
sort=🇭🇰>🇸🇬>🇯🇵>🇺🇸
不要用花样字体
