### ISSUE TITLE
Quantumult X 资源解析器 参数文本带空格是否需要加引号？

### ISSUE THREAD

**Issue by Mosney** [KOP-XIAO/QuantumultX#4]
机场提供的节点名称中英文间带有空格 例如`香港 IPLC 2` `台湾 BGP 3`
`in=香港 IPLC+台湾 BGP &emoji=1&tfo=1`
其中的`香港 IPLC` `台湾 BGP`中间有一个空格，这种情况是否需要加引号

**Comment by KOP-XIAO** [comment]
空格需要 urlencode，也就是%20 代替 “香港%20IPLC”

**Comment by Mosney** [comment]
清楚了 感谢
