### ISSUE TITLE
解析just my socks订阅的问题

### ISSUE THREAD

**Issue by superszy** [KOP-XIAO/QuantumultX#40]
发现解析器对于just my socks订阅中的ss节点解析不正确，导致无法连接。

原因是订阅链接中的信息，包含由 @字符 分隔的 密码字段 和 服务器地址字段，但是解析器没有把它们分开，导致了密码错误，并误将节点名当作了服务器地址。

例如，对于以下样例订阅信息
c3M6Ly9ZV1Z6TFRJMU5pMW5ZMjA2Y0dGemMyRmlkMjl5WkVBNU15NDBNUzR4TmpndU56RTZNVEl6TkRVPSNKTVMtNjkzMjVAYzEyczEuamFtamFtcy5uZXQ6MTIzNDUK

正确解析应为
shadowsocks=93.41.168.71:12345, method=aes-256-gcm, password=passabword, fast-open=false, udp-relay=false, tag=JMS-69325@c12s1.jamjams.net:12345

但解析器返回为
shadowsocks=c12s1.jamjams.net:12345, method=aes-256-gcm, password=passabword@93.41.168.71, fast-open=false, udp-relay=false, tag=JMS-69325@c12s1.jamjams.net:12345

非常感谢~

**Comment by KOP-XIAO** [comment]
应该修复了。

**Comment by superszy** [comment]
更新之后没有问题了，太棒了~
