### ISSUE TITLE
解析 clash 支持的 vmess ？

### ISSUE THREAD

**Issue by wmjlxl** [KOP-XIAO/QuantumultX#46]
你好。

请问能解析 clash 下支持的如下给 Quantumultx 用么？

- {name: 日区, server: jp.aabbcc.com, port: 1111, type: vmess, uuid: 0FAE1D02-B521-4649-9C5A-27656D2BEDF6, alterId: 32, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-path: /js, ws-headers: {Host: jp.aabbcc.com}, udp: true}

谢谢。

**Comment by wmjlxl** [comment]
add comment

**Comment by WSL33099** [comment]
能用

**Comment by wmjlxl** [comment]
> 能用
请问你有试过解析如下么？ 可以看看你得出什么结果么？

{name: 日区, server: jp.aabbcc.com, port: 1111, type: vmess, uuid: 0FAE1D02-B521-4649-9C5A-27656D2BEDF6, alterId: 32, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-path: /js, ws-headers: {Host: jp.aabbcc.com}, udp: true}

谢谢。

**Comment by KOP-XIAO** [comment]
[
![CleanShot 2021-08-23 at 11 31 57@2x](https://user-images.githubusercontent.com/45581750/130386470-e9b3a6a1-ed3c-4d98-bf69-504f89516b47.png)
](URL)

这不是正常解析出来了吗？
前提是你把 【日区】后的 ，换成 ,
