### ISSUE TITLE
Syntax error found in configurations file at line 7

### ISSUE THREAD

**Issue by yq930825** [KOP-XIAO/QuantumultX#52]
![F1193658-A4D8-493A-84F5-879A764832FB](https://user-images.githubusercontent.com/11594774/137567297-8b21579e-ef4e-4f2d-b990-f3ad53b90362.jpeg)

**Comment by yq930825** [comment]
QuantumultX v1.0.25-build609

**Comment by KOP-XIAO** [comment]
lan=zh-CN，链接是不应该有空格的

链接填错这种事就不用反馈了

**Comment by yq930825** [comment]
> lan=zh-CN，链接是不应该有空格的
> 
> 链接填错这种事就不用反馈了

Thanks
