### ISSUE TITLE
streaming-ui-check 中getLocationInfo()总是超时

### ISSUE THREAD

**Issue by fangpidedongsun** [KOP-XIAO/QuantumultX#55]
环境背景：使用解锁美区Disney的日本节点，观看正常。使用检测脚本提示超时。

查看脚本发现问题出现在getLocationInfo() 时，正常新加坡节点并解锁Disney时
日志：locationinfo:200 ---->getLocationInfo: countryCode=SG, inSupportedLocation=true

但当使用解锁了美区Disney的日本节点时
日志：locationinfo:200 ---->不会再执行getLocationInfo&inSupportedLocation了。
不知道是哪里出了问题，烦请大佬看一下。
谢谢！！

**Comment by KOP-XIAO** [comment]
单独的disney检测脚本，是否正常呢？

**Comment by fangpidedongsun** [comment]
> 单独的disney检测脚本，是否正常呢？

也是检测超时，但是会提示 testDisneyPlus: region=undefined, status=-1

**Comment by KOP-XIAO** [comment]
出现 locationinfo:200   的话， 就已经是在执行 getLocationInfo() 了。
应该是返回下面这个时出错了。但我没类似节点，复现不了
let {
        inSupportedLocation,
        location: { countryCode },
      } = JSON.parse(data)?.extensions?.sdk?.session
