### ISSUE TITLE
上游 “节点示范” 和 “部分重写规则” 的地址失效

### ISSUE THREAD

**Issue by neatgz** [KOP-XIAO/QuantumultX#62]
1、QuantumultX_Profiles.conf 第 153 154 行，两个节点示范，上游重新命名了 “Rename **server.txt** to **server.snippet**”  “Rename **server-complete.txt** to **server-complete.snippet**”
2、第202行，神机复写(🎵️TikTok-JP) ，上游貌似已不再提供。

**Comment by KOP-XIAO** [comment]
已更改
