### ISSUE TITLE
0427更新后脚本通知无法关闭

### ISSUE THREAD

**Issue by superszy** [KOP-XIAO/QuantumultX#64]
0427更新后，对于server类型的解析，默认开启了解析，且ntf=0无法关闭。

谢谢

**Comment by KOP-XIAO** [comment]
什么通知？能截图么

没有复现

**Comment by superszy** [comment]
你好，就是QX更新订阅时弹出的脚本通知，如图

![photo_2022-04-28_10-25-52](https://user-images.githubusercontent.com/3102177/165664317-68f154d4-cd81-42d9-9c9c-07bf92515448.jpg)

**Comment by KOP-XIAO** [comment]
已修复

**Comment by superszy** [comment]
更新后没有问题了，非常感谢
