### ISSUE TITLE
如何在 server_remote 中，为订阅单独指定server_check_url参数

### ISSUE THREAD

**Issue by Infatuation-Fei** [KOP-XIAO/QuantumultX#65]
看了您的配置解读中写了"可以在 server_local/remote 中，为节点、订阅单独指定server_check_url参数"，我尝试了一下，在server_remote为订阅指定server_check_url没有效果，只在server_local中有效，请教一下在server_remote中为订阅单独指定server_check_url参数该怎么写呢

**Comment by KOP-XIAO** [comment]
远程节点内容中写，而不是链接的位置写。

**Comment by Infatuation-Fei** [comment]
OK，明白了，感谢。
也看到您的解析器支持了指定server_check_url参数👍👍👍
