### ISSUE TITLE
解析器国旗图标错乱

### ISSUE THREAD

**Issue by DoingDog** [KOP-XIAO/QuantumultX#67]
解析器出来的国旗图标有错乱

![BE86AE51-6BD2-4C77-846D-ABDD104137DA](https://user-images.githubusercontent.com/72430078/166706220-13d17a1a-e190-4078-89e8-2fc399390e36.jpeg)

感谢大佬

**Comment by DoingDog** [comment]
改变顺序，加入空格似乎可以解决（？

var Lmoji = { 
    "🇧🇪": ["BE ", "BE-", "比利時", "比利时"],
    "🇺🇦": ["UA ", "UA-", "烏克蘭", "乌克兰"],
    "🇭🇷": ["克罗地亚", "HR ", "HR-", "克羅地亞"],
    "🇳🇬": ["尼日利亚", "NG ", "NG-", "尼日利亞", "拉各斯"],
    "🇸🇰": ["斯洛伐克", "SK ", "SK-"],
    "🇷🇸": ["RS ", "RS-", "塞尔维亚"],
    "🇲🇩": ["摩爾多瓦", "MD ", "MD-", "摩尔多瓦"],
    "🇩🇰": ["DK ", "DK-", "DNK", "丹麦", "丹麥"],
    "🇪🇸": ["ES ", "ES-", "西班牙", "Spain"],
    "🇫🇷": ["FR ", "FR-", "France", "法国", "法國", "巴黎"],
    "🇬🇧": ["UK ", "GB ", "UK-", "GB-", "England", "United Kingdom", "英国", "伦敦"],
    "🇲🇴": ["MO ", "MO-", "Macao", "Macau", "MAC", "澳门", "澳門", "CTM"],
    "🇮🇩": ["ID ", "ID-", "Indonesia", "印尼", "印度尼西亚", "雅加达"],
    "🇮🇳": ["India", "IND", "INDIA", "印度", "孟买", "Mumbai", "IN ", "IN-"],
    "🇮🇸": ["IS ", "IS-", "ISL", "冰岛", "冰島"],
    "🇲🇽️": ["MEX", "MX ", "MX-", "墨西哥"],
    "🇲🇾": ["MY ", "MY-", "Malaysia", "MALAYSIA", "大馬", "馬來西亞", "吉隆坡", "馬來", "马来"],
    "🇳🇱": ["NL ", "NL-", "Netherlands", "荷兰", "荷蘭", "尼德蘭", "阿姆斯特丹"],
    "🇵🇭": ["PH ", "PH-", "Philippines", "菲律宾", "菲律賓"],
    "🇷🇴": ["RO ", "RO-", "罗马尼亚"],
    "🇧🇾": ["BY ", "BY-", "白俄罗斯", "白俄羅斯"],
    "🇰🇵": ["KP ", "朝鲜"],
    "🇸🇪": ["SE ", "SE-", "Sweden", "瑞典"],
    "🇹🇭": ["TH ", "TH-", "Thailand", "泰国", "泰國", "曼谷"],
    "🇹🇷": ["TR ", "TR-", "TUR", "Turkey", "土耳其", "伊斯坦布尔"],
    "🇻🇳": ["VN ", "VN-", "越南", "胡志明市"],
    "🇮🇹": ["Italy", "IT ", "IT-", "Nachash", "意大利", "米兰", "義大利"],
    "🇦🇪": ["United Arab Emirates", "阿联酋", "AE ", "AE-"],
    "🇧🇷": ["BR ", "BR-", "Brazil", "巴西", "圣保罗"],
    "🇦🇷": ["AR ", "AR-", "Argentina", "阿根廷"],
    "🇳🇴": ["Norway", "挪威", "NO ", "NO-"],
    "🇵🇱": ["PL ", "PL-", "POL", "波兰", "波蘭"],
    "🇨🇾": ["CY ", "CY-", "塞浦路斯"],
    "🇩🇪": ["DE ", "DE-", "German", "GERMAN", "德国", "德國", "法兰克福", "京德", "滬德", "廣德", "沪德", "广德"],
    "🇰🇷": ["KR ", "KR-", "Korea", "KOR", "韩国", "首尔", "韓", "春川"],
    "🇷🇺": ["RU ", "RU-", "Russia", "俄罗斯", "毛子", "俄国", "俄羅斯", "伯力", "莫斯科", "圣彼得堡", "西伯利亚", "新西伯利亚", "京俄", "杭俄", "廣俄", "滬俄", "广俄", "沪俄"],
    "🇦🇺": ["AU ", "AU-", "Australia", "Sydney", "澳大利亚", "澳洲", "墨尔本", "悉尼", "土澳", "京澳", "廣澳", "滬澳", "沪澳", "广澳"],
    "🇨🇦": ["CA ", "CA-", "Canada", "CANADA", "CAN", "Waterloo", "加拿大", "蒙特利尔", "温哥华", "楓葉", "枫叶", "滑铁卢", "多伦多"],
    "🇦🇿": ["阿塞拜疆"],
    "🇵🇰": ["巴基斯坦"],
    "🇰🇭": ["柬埔寨"],
    "🇦🇹": ["奥地利", "奧地利", "Austria", "维也纳"],
    "🇧🇬": ["保加利亚", "保加利亞", "Bulgaria"],
    "🇨🇭": ["瑞士", "苏黎世", "Switzerland"],
    "🇨🇿": ["Czechia", "捷克"],
    "🇸🇦": ["沙特", "迪拜"],
    "🇨🇱": ["智利"],
    "🇳🇿": ["新西蘭", "新西兰"],
    "🇬🇷": ["希腊", "希臘"],
    "🇪🇬": ["埃及"],
    "🇮🇲": ["马恩岛", "馬恩島"],
    "🇵🇹": ["葡萄牙"],
    "🇲🇳": ["蒙古"],
    "🇵🇪": ["秘鲁", "祕魯"],
    "🇨🇴": ["哥伦比亚"],
    "🇪🇪": ["爱沙尼亚"],
    "🇲🇰": ["马其顿", "馬其頓"],
    "🇲🇹": ["马耳他"],
    "🇻🇪": ["委内瑞拉"],
    "🇧🇦": ["波黑共和国", "波黑"],
    "🇬🇪": ["格魯吉亞", "格鲁吉亚"],
    "🇦🇱": ["阿爾巴尼亞", "阿尔巴尼亚"],
    "🇨🇷": ["哥斯达黎加"],
    "🇹🇳": ["突尼斯"],
    "🇵🇦": ["巴拿马", "巴拿馬"],
    "🇮🇷": ["伊朗"],
    "🇯🇴": ["约旦"],
    "🇺🇾": ["乌拉圭"],
    "🇰🇪": ["肯尼亚"],
    "🇰🇬": ["吉尔吉斯坦", "吉尔吉斯斯坦"],
    "🇳🇵": ["尼泊尔"],
    "🇽🇰": ["科索沃"],
    "🇲🇦": ["摩洛哥"],
    "🇱🇺": ["卢森堡"],
    "🇮🇱": ["Israel", "以色列"],
    "🇱🇻": ["Latvia", "Latvija", "拉脱维亚"],
    "🇧🇩": ["孟加拉"],
    "🇿🇦": ["South Africa", "南非"],
    "🇫🇮": ["Finland", "芬兰", "芬蘭", "赫尔辛基"],
    "🇰🇿": ["哈萨克斯坦"],
    "🇸🇮": ["斯洛文尼亚"],
    "🇭🇺": ["匈牙利", "Hungary"],
    "🇱🇹": ["立陶宛"],
    "🇮🇪": ["Ireland", "IRELAND", "爱尔兰", "愛爾蘭", "都柏林"],
    "🇹🇼": ["TW", "TW-", "Taiwan", "TAIWAN", "台湾", "台灣", "台北", "台中", "新北", "彰化", "CHT", "HINET"],
    "🇺🇸": ["US", "US-", "USA", "America", "United States", "美国", "美國", "京美", "波特兰", "达拉斯", "俄勒冈", "凤凰城", "费利蒙", "硅谷", "矽谷", "拉斯维加斯", "洛杉矶", "圣何塞", "圣克拉拉", "西雅图", "芝加哥", "沪美", "哥伦布", "纽约"],
    "🇸🇬": ["SG", "SG-", "Singapore", "SINGAPORE", "新加坡", "狮城", "沪新", "京新", "泉新", "穗新", "深新", "杭新", "广新", "廣新", "滬新"],
    "🇯🇵": ["JP", "JP-", "Japan", "JAPAN", "日本", "东京", "大阪", "埼玉", "沪日", "穗日", "川日", "中日", "泉日", "杭日", "深日", "辽日", "广日"],
    "🇭🇰": ["HK", "HK-", "Hongkong", "Hong Kong", "HongKong", "HONG KONG", "香港", "深港", "沪港", "呼港", "HKT", "HKBN", "HGC", "WTT", "CMI", "穗港", "京港"],
    "🇨🇳": ["CN", "CN-", "China", "回国", "中国", "中國", "江苏", "北京", "上海", "广州", "深圳", "杭州", "徐州", "青岛", "宁波", "镇江", "back"],
    "🇪🇺": ["EU", "EU-", "欧盟", "欧罗巴", "欧洲"],
    "🌏": ["亚洲"],
    "🏳️‍🌈": ["流量", "时间", "应急", "过期", "Bandwidth", "expire"]
  }

**Comment by KOP-XIAO** [comment]
那别人节点没有空格怎么办哦？

要怪就怪你这节点名字太多信息了

**Comment by DoingDog** [comment]
好的，我重命名一下节点就行了。谢谢
