### ISSUE TITLE
作者考虑将 switch-check-*.js 脚本加上按延迟排序吗？

### ISSUE THREAD

**Issue by 1nC0deWeTrust** [KOP-XIAO/QuantumultX#68]
js 具体写法不太懂，但我看代码里是直接将支持的节点 push 到 OKList，然后暴力延迟后取了[1]来 set_policy_state ，对节点的选择并没有加入低延迟优先的逻辑，但这个逻辑又确实很重要😂，请问是否有打算将其加上呢？另外我对你 set_policy_state  时取数组第二个元素很好奇，没想明白为啥这么干。

**Comment by KOP-XIAO** [comment]
因为list里第1个元素是一个描述啊  “支持节点 ➟ ”。
所以就是取测试完第 1⃣️ 个支持的。

**Comment by 1nC0deWeTrust** [comment]
@KOP-XIAO 
抱歉抱歉😂，忽略了这个。
按延迟排序这个逻辑可以考虑加进去吗？

**Comment by KOP-XIAO** [comment]
已更新
