### ISSUE TITLE
用于resource-parser的所有flag emoji

### ISSUE THREAD

**Issue by shnode** [KOP-XIAO/QuantumultX#71]
用于resource-parser的所有flag emoji

现在好多机场都开站了全球落地计划，故整理了一份完整的flag

[emoji.txt](https://github.com/KOP-XIAO/QuantumultX/files/8727461/emoji.txt)

**Comment by KOP-XIAO** [comment]
emoji靠名字跟列表顺序匹配，你这个顺序会有些问题

**Comment by shnode** [comment]
嗯，是的，那天发现了，因为我做list时候是按照字母顺序来的，之后我把波兰和中国都放在最后，测了FlowerCloud，AMY，IMM和TAG这些节点命名正经的大机场，以及其他一些命名正常的但是不怎么出名的机场，旗帜标记没问题了，就FlowerCloud还有个traffic要放到海盗旗那栏里面。

当然，如果把二位字母和三位字母都编辑进来的话，可能出错的会增多，这就走一步看一步吧，主要这份东西还是服务中文用户

**Comment by KOP-XIAO** [comment]
解析器现在用的这个，会有什么问题吗

**Comment by shnode** [comment]
解析器除了TAG总是少旗帜之外，暂时没发现其他其他站少旗帜
