### ISSUE TITLE
蜂窝数据网络下暂停工作设置书写

### ISSUE THREAD

**Issue by cutbuzz** [KOP-XIAO/QuantumultX#81]
;ssid_suspended_list，让 Quantumult X 在特定 Wi-Fi 网络下暂停工作(仅 task 模块会继续工作)，多个Wi-Fi用“,”连接
;ssid_suspended_list=Asus, Shawn-Wifi

教程里写的是在特定的Wi-Fi网络下暂停工作，请问想设置在4G网络暂停工作该怎么写呢？求指点

**Comment by KOP-XIAO** [comment]
没这参数。有需求去邮件跟开发者提。
