### ISSUE TITLE
检测chatGPT提示可以但是实际不可用

### ISSUE THREAD

**Issue by jaychoubaby** [KOP-XIAO/QuantumultX#90]
用streaming-ui-check.js检测提示可以访问，

我的ip是155.248.160.186，打开chatGPT提示访问被拒绝，请问是什么问题

**Comment by KOP-XIAO** [comment]
不知道。检测逻辑是别人的

**Comment by shnode** [comment]
目前GPT的检测还是只能参考，像大厂的IP已经都ban完了，记住这点就行了
