### ISSUE TITLE
nf-ui-check和streaming-ui-check，对于NF检测结果不同

### ISSUE THREAD

**Issue by tyhunter** [KOP-XIAO/QuantumultX#91]
同一个节点，确认是仅支持自制剧（绝命毒师搜不到），NF-UI-CHECK显示的结果是对的：仅支持自制剧，streaming-ui-check显示的是完整支持，是不是检测的逻辑不一致

**Comment by harveyhuangw** [comment]
可能是FILM_ID，80062035 的问题，我尝试换了 81280792 这个ID，检测目前是正常。

**Comment by KOP-XIAO** [comment]
更新
