### ISSUE TITLE
no-system配置excluded_ssids后报错

### ISSUE THREAD

**Issue by davidu2003** [KOP-XIAO/QuantumultX#92]
> [dns]
; 禁用系统 DNS（no-system） 以及 ipv6
;no-system
;no-ipv6
;支持参数 excluded_ssids , included_ssids(1.0.29+) 指定在特定 Wi-Fi下失效/生效

配置成 
`no-system, excluded_ssids=somewifi`的时候，会报配置文件错误，请大佬帮忙看看，谢谢

**Comment by KOP-XIAO** [comment]
不支持 no-system这种指定排除
