### ISSUE TITLE
[建议]Clash Rule Provider 通配符转换优化

### ISSUE THREAD

**Issue by 1nC0deWeTrust** [KOP-XIAO/QuantumultX#95]
是否可以增加将 clash 这两条规转换成 qx 中的 host-wildcard,xxx,xxx？
![image](https://user-images.githubusercontent.com/25895481/230305088-54bef369-794e-4682-9127-3503bd1ce60f.png)

clash config wildcard 语法说明
https://lancellc.gitbook.io/clash/clash-config-file/syntax#wildcard

测试链接👇
https://gist.githubusercontent.com/1nC0deWeTrust/7e62bf262071ca89a2637a705032bb5b/raw

**Comment by 1nC0deWeTrust** [comment]
parser.js 解析结果如下：
![image](https://user-images.githubusercontent.com/25895481/230307546-6cb791c1-31bc-49d1-8e42-83f7cf6dfc1c.png)

转换后的规则实际上已经不是原规则要表达的意思了。

**Comment by KOP-XIAO** [comment]
更新

**Comment by 1nC0deWeTrust** [comment]
想基于你的代码增加 clash 中通配符`*`在中间的情况，但是在我fork了你的代码并在qx中引用了我仓库中的parser.js后，`!/\*|\+/.test(cnt[0])`这句代码一直就是false，改了多次不成功，可以麻烦加上这个逻辑吗？

后面我即使改成`resource_parser_url= https://fastly.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/resource-parser.js
`，下面这个去广告的yaml会全部解析成wildcard，这样会严重降低性能。我多次测试，甚至把qx卸载重装了。

去广告链接：https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml
